### ISSUE TITLE
How can I set the size of the ExpandableFab

### ISSUE THREAD

**Issue by alperefesahin** [zuvola/flutter_expandable_fab#10]
Hey, I want to set the size of the `ExpandableFab` as `FloatActionButton.large` or `FloatActionButton.small`, etc. Is it possible? If it is, how can I do this?

Thanks.

**Comment by alper-efe-sahin** [comment]
You may update the package actually. For the `FloatActionButton`, just set `.small` or `.large `.

**Comment by zuvola** [comment]
Please use Ver 1.7.0.

Allow changing the size of the FAB #12
