### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by MdFarhanRaja** [zuvola/flutter_expandable_fab#11]
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
There are multiple heroes that share the same tag within a subtree. Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag. In this case, multiple heroes had the following tag: <default FloatingActionButton tag> # Here is the subtree for one of the offending heroes: Hero. Error thrown during a scheduler callback.

**Comment by zuvola** [comment]
Try to make hero tags with unique values.
Or can you submit a minimal sample code that I can reproduce?

**Comment by linsvensson** [comment]
I'm having the same problem by just adding the code from "Getting started".

**Comment by zuvola** [comment]
FloatingActionButton needs a heroTag for screen transitions.
Please see the revised sample in "Getting started".
