### ISSUE TITLE
Position of FAB to Left or Right

### ISSUE THREAD

**Issue by devrajraut** [zuvola/flutter_expandable_fab#13]
This is a very Good looking Widget, but I didn't find any option to shift the FAB to the Left side. The Positioned Widget in the AnimatedBuilder only has right and bottom arguments. Kindly update to set FAB programatically to any desired location. Thanks.

**Comment by nietsmmar** [comment]
Would be nice to be able to set some offset to the position too. I have a custom bottom bar and currently my fab is located on top of this bar because I can't manipulate the fab location.

**Comment by zuvola** [comment]
Thank you for your proposal.
As I don't have much time to implement it, it would be helpful if someone could provide a PR.

**Comment by r0b3rth4ns3n** [comment]
obviously i understand that you don't have much time to implement :) just want to let you know again that a "left-hand-mode" would be much appreciated !

**Comment by zuvola** [comment]
I am currently preparing a new update that will include a left-handed mode, so please be patient.

**Comment by zuvola** [comment]
This feature was added in version 2.0.0. Please check it.
