### ISSUE TITLE
Crash on close when only 1 children

### ISSUE THREAD

**Issue by lubbo** [zuvola/flutter_expandable_fab#14]
If you add only one children,
on open it will be positioned on upper left screen corner
on close it raises an exception:

```
'package:flutter/src/rendering/box.dart': Failed assertion: line 2902 pos 18: 'transformed == position - childParentData.offset': is not true.
```

**Comment by zuvola** [comment]
I have fixed it in v1.7.1, please check it out.
Thank you for reporting the bug.
