### ISSUE TITLE
onTap executed with action button closed

### ISSUE THREAD

**Issue by Sergiobi9** [zuvola/flutter_expandable_fab#18]
Hello,

I'm using this library. Which is awesome! 

I don't know if I'm not doing it correctly. I have an expandable fab on the bottom right of the screen which shows three options when pressed: Upload camera foto, upload gallery photo, or upload file. Till here all is correct.

The problem happens when I have a list view for example, which is reaching almost the bottom of the screen. I try to press an item at the bottom of the screen, and instead of doing the onPressed function of that item, it executes the onTap function of the floating expandable fab, even though it is closed.

I don't know if you are facing this issue.

**Comment by mecidr** [comment]
I am also experiencing the same issue. In my case I have  Tabbar as bottomNavigationBar of Scaffold. Tapping Tabbar elements triggers onTap function of one of the buttons in Expandable tab

**Comment by zuvola** [comment]
Thank you for reporting the bug.
I have fixed it in v1.8.1, please check it out.

**Comment by mecidr** [comment]
> Thank you for reporting the bug. I have fixed it in v1.8.1, please check it out.

Sure :) 
I guess the issue can be closed now
