### ISSUE TITLE
heroTag

### ISSUE THREAD

**Issue by r0b3rth4ns3n** [zuvola/flutter_expandable_fab#21]
why is it important to set `heroTag: null` for the `children` of `ExpandableFab` ?

**Comment by zuvola** [comment]
This is a restriction on the FloatingActionButton, not on the flutter_expandable_fab.
If you use IconButton or something similar for your child buttons, you should not need to set heroTag.

https://api.flutter.dev/flutter/material/FloatingActionButton/heroTag.html
