### ISSUE TITLE
Overlay assertion error if both color and blur are specified.

### ISSUE THREAD

**Issue by pranavkumark13** [zuvola/flutter_expandable_fab#25]
### Describe the bug:
I tried setting both color and blur to the property overlayStyle as mentioned in the documentation, but I am facing an assertion error saying "'color== null || blur == null': is not true." In the example code provided, the color property in the overlayStyle is commented out. There is a requirement for us to have both color and blur. 

### To Reproduce:
Add this 
```
overlayStyle: ExpandableFabOverlayStyle(
          color: Colors.black.withOpacity(0.5),
          blur: 5,
        ),
```
to the ExpandableFab widget.

### Expected Behavior:
Overlaystyle should work by adding both color and blur. The Background of the fab button should have the color which is passed.

**Comment by zuvola** [comment]
Sorry for the delay in replying.
I have fixed the issue in 2.1.0, please check back.
