### ISSUE TITLE
Floating action button not closing!

### ISSUE THREAD

**Issue by Vivaldo-Roque** [zuvola/flutter_expandable_fab#29]
I updated flutter to version 3.24.0
I updated the plugin to version 2.2.0

And whenever I open the floating action button I can't close it using the close button, it just doesn't work.

**Comment by scotthmusson** [comment]
I am also seeing this issue with flutter 3.22.0, plugin 2.3.0.  The close button doesn't always work but the action buttons do. Also it appears that state of the extended fab is always open. Issue worse on iOS but can be replicated on Android.

[✓] Flutter (Channel stable, 3.22.0, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at /Users/scottmusson/fvm/versions/3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

**Comment by SantiagoSchez** [comment]
Still happening. 2.0.0 was the last version that doesn't have this bug.

**Comment by JYeop** [comment]
Why it is closed? It is a huge problem
