### ISSUE TITLE
Bad alignment when `closeButtonBuilder` returns a larger widget than `openButtonBuilder`

### ISSUE THREAD

**Issue by programotuojes** [zuvola/flutter_expandable_fab#30]
I'm using the `closeButtonBuilder` to provide an actionable item instead of using it just to close the expanded FAB. This is to prevent the user from moving their pointer to click on the most often used item.

I've wrapped the close button in a row to add a label and this made the close button wider than the open button, which resulted in the open button moving away from the screen edge:

![Screenshot_20240831_163952](https://github.com/user-attachments/assets/5ddadb8b-b171-4058-9b67-dd9d35fd1d0f)

When open:

![Screenshot_20240831_164004](https://github.com/user-attachments/assets/ea423a9c-26e1-4476-92b8-7ae32a590d3c)

I've implemented a hopefully universal solution here https://github.com/programotuojes/flutter_expandable_fab/commit/87cfec1e305d41648e64ba37b61c932cc4b44e23. With it, the button is placed back into the corner:

![Screenshot_20240831_170749](https://github.com/user-attachments/assets/0c6bb3f6-1680-4f9c-b6f0-f3c00c5ca932)

I can open a PR if this solution seems good enough.

**Comment by zuvola** [comment]
Thanks for the suggestion.
That sounds great, but there seems to be a compatibility issue.
When I run the EXAMPLE, it is misaligned as shown in the attached image.

How about making openCloseStackAlignment a property and set the default value to center?

<img width="159" alt="ss" src="https://github.com/user-attachments/assets/3b08b32a-e76a-4f65-9f11-11c600710145">

**Comment by programotuojes** [comment]
Sounds good!

That was my implementation :smile: but didn't want to add another configuration property and though using the existing `pos` would suffice. But a breaking change is definitely bad. Btw good call on checking example code. Didn't notice it in my code since I use regular sized FABs for open and closing.
