### ISSUE TITLE
Exception on Flutter Web

### ISSUE THREAD

**Issue by AliKarimiENT** [zuvola/flutter_expandable_fab#4]
This is my error 
Flutter verstion : **3.3.0**
![image](https://user-images.githubusercontent.com/57004354/190966300-b9c5af80-82dc-4afc-8ccb-f6cbe83b25fd.png)

**This is the code**
![image](https://user-images.githubusercontent.com/57004354/190966443-6cda108a-22ee-4545-8922-327f51fa1c75.png)

**When I don't click this error has occurred**

![image](https://user-images.githubusercontent.com/57004354/190966650-c7139c04-f8cb-4e03-8e22-a2e7d09ae1c7.png)

**but when I tap on it**

![image](https://user-images.githubusercontent.com/57004354/190966754-d65b4be5-4dba-42f0-afbe-2d12c932ab13.png)

**Comment by zuvola** [comment]
Thanks for the report.
Sorry, I did not check enough on the web.
This seems to be a bug on the Flutter side : [flutter/flutter#89433](https://github.com/flutter/flutter/issues/89433), but I have tried to work around it.
Please try version 1.5.2.

**Comment by AliKarimiENT** [comment]
> Thanks for the report.
> Sorry, I did not check enough on the web.
> This seems to be a bug on the Flutter side : [flutter/flutter#89433](https://github.com/flutter/flutter/issues/89433), but I have tried to work around it.
> Please try version 1.5.2.

Thanks my problem solved
