### ISSUE TITLE
why microtask is userd in offsetX()?

### ISSUE THREAD

**Issue by mrginpadd** [zuvola/flutter_expandable_fab#7]
I don't understand it . But when i delete the microtask, the animation is stuck and stopped.

**Comment by mrginpadd** [comment]
rarely happens, but there are

**Comment by zuvola** [comment]
Thank you for your report.
Since I am unable to reproduce the issue, could you please submit a minimal sample code that I can reproduce?

**Comment by mrginpadd** [comment]
library flutter_expandable_fab;

import 'dart:math' as math;
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../state/calendarState.dart';


/// 子菜单弹出的方向
enum ExpandableFabType { left }

/// 遮罩层样式类 模糊/颜色 二选一
@immutable
class ExpandableFabOverlayStyle {
  ExpandableFabOverlayStyle({
    this.color,
    this.blur,
  }) {
    assert(color == null || blur == null);
    assert(color != null || blur != null);
  }

  /// The color to paint behind the Fab.
  final Color? color;

  /// The strength of the blur behind Fab.
  final double? blur;
}

/// 展开状态下的  主菜单样式类
@immutable
class ExpandableFabCloseButtonStyle {
  const ExpandableFabCloseButtonStyle({
    this.child = const Icon(Icons.close),
    this.foregroundColor,
    this.backgroundColor,
  });

  /// The widget below the close button widget in the tree.
  final Widget child;

  /// The default foreground color for icons and text within the button.
  final Color? foregroundColor;

  /// The button's background color.
  final Color? backgroundColor;
}

///主菜单位置
class _ExpandableFabLocation extends StandardFabLocation {
  final ValueNotifier<ScaffoldPrelayoutGeometry?> scaffoldGeometry =
      ValueNotifier(null);

  //获取 scaffold 布局信息
  @override
  double getOffsetX(
      ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
    Future.microtask(() {
      this.scaffoldGeometry.value = scaffoldGeometry;
    });
    return 0;
  }

  @override
  double getOffsetY(
      ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
    return 0;
  }
}

/// Fab button that can show/hide multiple action buttons with animation.
@immutable
class ExpandableFab extends StatefulWidget {
  static final FloatingActionButtonLocation location = _ExpandableFabLocation();

  const ExpandableFab({
    Key? key,
    this.aboveBtn = const Icon(Icons.today),
    this.distance = 100,
    this.duration = const Duration(milliseconds: 250),
    this.fanAngle = 90, //子菜单弹出的角度
    this.initialOpen = false,
    this.type = ExpandableFabType.left,
    this.closeButtonStyle = const ExpandableFabCloseButtonStyle(),
    this.foregroundColor,
    this.backgroundColor,
    this.child = const Icon(Icons.menu),
    this.childrenOffset = const Offset(0, 0),
    required this.children,
    this.onOpen,
    this.afterOpen,
    this.onClose,
    this.afterClose,
    this.overlayStyle,
  }) : super(key: key);

  final Widget aboveBtn;

  /// Distance from children.
  final double distance;

  /// Animation duration.
  final Duration duration;

  /// Angle of opening when fan type.
  final double fanAngle;

  /// Open at initial display.
  final bool initialOpen;

  /// The type of behavior of this widget.
  final ExpandableFabType type;

  /// Style of the close button.
  final ExpandableFabCloseButtonStyle closeButtonStyle;

  /// The widget below this widget in the tree.
  final Widget child;

  /// For positioning of children widgets.
  final Offset childrenOffset;

  /// The widgets below this widget in the tree.
  final List<Widget> children;

  /// The default foreground color for icons and text within the button.
  final Color? foregroundColor;

  /// The button's background color.
  final Color? backgroundColor;

  /// Will be called before opening the menu.
  final VoidCallback? onOpen;

  /// Will be called after opening the menu.
  final VoidCallback? afterOpen;

  /// Will be called before the menu closes.
  final VoidCallback? onClose;

  /// Will be called after the menu closes.
  final VoidCallback? afterClose;

  /// Provides the style for overlay. No overlay when null.
  final ExpandableFabOverlayStyle? overlayStyle;

  @override
  State<ExpandableFab> createState() => ExpandableFabState();
}

class ExpandableFabState extends State<ExpandableFab>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _expandAnimation;
  bool _open = false;
  final CalendarStateController calendarStateController = Get.find();
  // double screenHeight = 0.0;

  /// Returns whether the menu is open
  bool get isOpen => _open;

  // bool floatShow = true;
  // var keyboardVisibilityController = KeyboardVisibilityController();

  /// 切换收起/展开
  void toggle() {
    setState(() {
      _open = !_open;
      if (_open) {
        widget.onOpen?.call();
        _controller.forward().then((value) {
          widget.afterOpen?.call();
        });
      } else {
        widget.onClose?.call();
        _controller.reverse().then((value) {
          widget.afterClose?.call();
        });
      }
    });
  }

  /// 修改fab按钮的大小
  Widget resizeBtn(Widget fab, {Size size = const Size(53, 53)}) {
    return SizedBox(
      width: size.width,
      height: size.height,
      child: FittedBox(child: fab),
    );
  }

  @override
  void initState() {
    super.initState();
    _open = widget.initialOpen;
    _controller = AnimationController(
      value: _open ? 1.0 : 0.0,
      duration: widget.duration,
      vsync: this,
    );
    _expandAnimation = CurvedAnimation(
      curve: Curves.fastOutSlowIn,
      reverseCurve: Curves.easeOutQuad,
      parent: _controller,
    );
    
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final location = ExpandableFab.location as _ExpandableFabLocation;
    Offset? offset;
    Widget? cache;

    //监听页面区域的变化
    return ValueListenableBuilder<ScaffoldPrelayoutGeometry?>(
      valueListenable: location.scaffoldGeometry,
      builder: ((context, geometry, child) {
        if (geometry == null) {
          return const SizedBox.shrink();
        }
        //设置主菜单x,  2*kFloatingActionButtonMargin 是主菜单距最右侧的间距
        final x = 30 + geometry.minInsets.right;

        final bottomContentHeight =
            geometry.scaffoldSize.height - geometry.contentBottom;

        //设置主菜单 y, 30 + kBottomNavigationBarHeight 是主菜单距最底侧的间距
        double y = 32 +
            kBottomNavigationBarHeight +
            math.max(geometry.minViewPadding.bottom, bottomContentHeight);
        

        //判断主菜单的位置是否变化，若变化则重新构建按钮组
        if (offset == null) {
          offset = Offset(x, y);
          cache = _buildButtons(offset!);
        }
        return cache!;
      }),
    );
  }

  ///构建按钮
  Widget _buildButtons(Offset offset) {
    final blur = widget.overlayStyle?.blur;
    return GestureDetector(
      onTap: () => toggle(),
      child: Stack(
        alignment: Alignment.bottomRight,
        children: [
          Positioned(
              //54 + 15
              bottom: offset.dy + 69,
              right: offset.dx,
              child: Obx(() {
                return calendarStateController.today.value
                    ? Container()
                    : resizeBtn(widget.aboveBtn);
              })),
          //如果是展开状态  显示毛玻璃效果
          if (blur != null)
            //根据展开状态确定是否禁用交互/ 展示毛玻璃
            IgnorePointer(
              ignoring: !_open,
              child: TweenAnimationBuilder<double>(
                tween: Tween<double>(begin: 0.0, end: _open ? blur : 0.0),
                duration: widget.duration,
                curve: Curves.easeInOut,
                builder: (_, value, child) {
                  if (value < 0.001) {
                    return child!;
                  }
                  //使用 ImageFilter.blur 制造的模糊效果
                  return BackdropFilter(
                    // blendMode:BlendMode.dstATop,
                    filter: ImageFilter.blur(sigmaX: value, sigmaY: value),
                    child: child,
                  );
                },
                child: Container(color: Colors.transparent),
              ),
            ),
          //展示子按钮
          ..._buildExpandingActionButtons(offset),
          Transform.translate(
            offset: -offset,
            child: resizeBtn(_buildTapToOpenFab()),
          ),
        ],
      ),
    );
  }

  ///子按钮组
  List<Widget> _buildExpandingActionButtons(Offset offset) {
    final children = <Widget>[];
    final count = widget.children.length;
    // final step = widget.fanAngle / (count - 1);
    //依次确定子按钮的位置
    for (var i = 0; i < count; i++) {
      final double dir, dist;
      //判断按钮弹出方向
      switch (widget.type) {
        case ExpandableFabType.left:
          dir = 0;
          dist = widget.distance * (i + 1);
          break;
      }
      children.add(
        _ExpandingActionButton(
          directionInDegrees: dir + (90 - widget.fanAngle) / 2,
          maxDistance: dist,
          progress: _expandAnimation,
          offset: offset + widget.childrenOffset,
          child: widget.children[i],
        ),
      );
    }
    return children;
  }

  ///展开状态时 的主菜单
  Widget _buildTapToOpenFab() {
    final duration = widget.duration;
    return IgnorePointer(
      ignoring: _open,
      child: FloatingActionButton(
        hoverElevation: 0.0,
        highlightElevation: 0.0,
        elevation: 0.0,
        shape: const CircleBorder(),
        heroTag: null,
        foregroundColor: widget.foregroundColor,
        backgroundColor: widget.backgroundColor,
        onPressed: toggle,
        child: AnimatedRotation(
          duration: duration,
          turns: _open ? -5 / 8 : 0,
          child: widget.child,
        ),
      ),
    );
  }
}

///子按钮类
@immutable
class _ExpandingActionButton extends StatelessWidget {
  const _ExpandingActionButton({
    required this.directionInDegrees,
    required this.maxDistance,
    required this.progress,
    required this.child,
    required this.offset,
  });

  final double directionInDegrees;
  final double maxDistance;
  final Animation<double> progress;
  final Offset offset;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: progress,
      builder: (context, child) {
        final pos = Offset.fromDirection(
          //移动方向
          directionInDegrees * (math.pi / 180.0),
          //移动距离
          progress.value * maxDistance,
        );
        return Positioned(
          right: offset.dx + pos.dx,
          bottom: offset.dy + pos.dy,
          child: child!,
        );
      },
      child: FadeTransition(
        opacity: progress,
        child: child,
      ),
    );
  }
}

**Comment by zuvola** [comment]
Please provide the minimum code that works.
What matters is that it works and is minimal.

**Comment by mrginpadd** [comment]
> Please provide the minimum code that works. What matters is that it works and is minimal.

How about future.delay ?
